apiVersion: apps/v1
kind: Deployment
metadata:
  name: localkart-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: localkart-api
  template:
    metadata:
      labels:
        app: localkart-api
    spec:
      containers:
        - name: api
          image: localkart/api:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: localkart-api
spec:
  selector:
    app: localkart-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP

